# Generated by Django 5.2.5 on 2026-08-18 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('formation', models.CharField(default='4-3-3', max_length=30)),
                ('style', models.CharField(default='High Press', max_length=60)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TacticalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_formation', models.CharField(max_length=30)),
                ('opponent_style', models.CharField(max_length=60)),
                ('attacking_strength', models.CharField(max_length=20)),
                ('midfield_strength', models.CharField(max_length=20)),
                ('defensive_strength', models.CharField(max_length=20)),
                ('team_style', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='tactical.opponent')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=30)),
                ('approach', models.CharField(max_length=180)),
                ('reason', models.TextField()),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='tactical.tacticaldecision')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('season', models.CharField(default='2025 / 26', max_length=40)),
                ('style', models.CharField(default='Possession with patient build-up', max_length=120)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tacticaldecision',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tactical.team'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=60)),
                ('number', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tactical.team')),
            ],
        ),
        migrations.AddField(
            model_name='opponent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='tactical.team'),
        ),
    ]
